####Analyses for Fitness Data####
#Updated 2022-04-13
#Based on files generated from previous scripts
#Analyses includes ANOVAs, general linear mixed effect models, linear models and linear mixed effect models
#Plots by ggplot2 with gridExtra
#R version 4.1.0 (2021-05-18)
#Packages used - car, dplyr, emmeans, ggplot2, gridExtra and MASS
#First generate files from "File S1.R" and "File S2.R"


####install prerequisite packages####
install.packages(c("car", "dplyr", "emmeans", "MASS", "lme4", "DHARMa"))

####Parental Stats####
#####Import data#####
setwd("C:/Target/Directory")
#Change to directory containing "Table S1.txt"
#Note below files generated by parental environment script ("File S1.R")

C1_novel <- read.delim("Stats/Parents_Cross1_Novel.txt")
C2_novel <- read.delim("Stats/Parents_Cross2_Novel.txt")
C3_novel <- read.delim("Stats/Parents_Cross3_Novel.txt")

C1_home <- read.delim("Stats/Parents_Cross1_Home.txt")
C2_home <- read.delim("Stats/Parents_Cross2_Home.txt")
C3_home <- read.delim("Stats/Parents_Cross3_Home.txt")

#####Home environment stats#####
LiAc0.01_home <- subset(C1_home, Population == "P2" & Environment == "LiAc 0.02M")
LiAc0.01_home$Population <- "LiAc0.01"

LiAc0.02_home <- subset(C2_home, Population == "P2" & Environment == "LiAc 0.02M")
LiAc0.02_home$Population <- "LiAc0.02"

NaCl_home <- subset(C3_home, Population == "P1" & Environment == "NaCl 0.325M")
NaCl_home$Population <- "NaCl"

EtOH_home <- subset(C3_home, Population == "P2" & Environment == "1-Butanol 1.5%")
EtOH_home$Population <- "EtOH"

library(dplyr)
NaCl_yield <- NaCl_home %>% group_by(Population, Generation, Environment) %>% summarise(mean_yield = mean(Phenotypes.ExperimentGrowthYield, na.rm = TRUE),  sd = sd(Phenotypes.ExperimentGrowthYield, na.rm = TRUE), n = n_distinct(Phenotypes.ExperimentGrowthYield, na.rm = TRUE))
NaCl_yield$ci <- 1.96*(NaCl_yield$sd/sqrt(NaCl_yield$n))

LiAc0.01_yield <- LiAc0.01_home %>% group_by(Population, Generation, Environment) %>% summarise(mean_yield = mean(Phenotypes.ExperimentGrowthYield, na.rm = TRUE),  sd = sd(Phenotypes.ExperimentGrowthYield, na.rm = TRUE), n = n_distinct(Phenotypes.ExperimentGrowthYield, na.rm = TRUE))
LiAc0.01_yield$ci <- 1.96*(LiAc0.01_yield$sd/sqrt(LiAc0.01_yield$n))

LiAc0.02_yield <- LiAc0.02_home %>% group_by(Population, Generation, Environment) %>% summarise(mean_yield = mean(Phenotypes.ExperimentGrowthYield, na.rm = TRUE),  sd = sd(Phenotypes.ExperimentGrowthYield, na.rm = TRUE), n = n_distinct(Phenotypes.ExperimentGrowthYield, na.rm = TRUE))
LiAc0.02_yield$ci <- 1.96*(LiAc0.02_yield$sd/sqrt(LiAc0.02_yield$n))

EtOH_yield <- EtOH_home %>% group_by(Population, Generation, Environment) %>% summarise(mean_yield = mean(Phenotypes.ExperimentGrowthYield, na.rm = TRUE),  sd = sd(Phenotypes.ExperimentGrowthYield, na.rm = TRUE), n = n_distinct(Phenotypes.ExperimentGrowthYield, na.rm = TRUE))
EtOH_yield$ci <- 1.96*(EtOH_yield$sd/sqrt(EtOH_yield$n))

#mean at each generation measured, including founder
N0 <-subset(NaCl_yield, Generation == "0")
N3 <-subset(NaCl_yield, Generation == "300")
#Max at 300 gens
((N3$mean_yield-N0$mean_yield)/N0$mean_yield)*100
#13.7% increase
N1K <-subset(NaCl_yield, Generation == "1000")
#Endpoint of adaptation
((N1K$mean_yield-N0$mean_yield)/N0$mean_yield)*100
#6.14% increase

L1_0 <-subset(LiAc0.01_yield, Generation == "0")
L1_3 <-subset(LiAc0.01_yield, Generation == "300")
#Max at 300 gens
((L1_3$mean_yield-L1_0$mean_yield)/L1_0$mean_yield)*100
#130.30% increase
L1_7 <-subset(LiAc0.01_yield, Generation == "700")
#Endpoint of adaptation
((L1_7$mean_yield-L1_0$mean_yield)/L1_0$mean_yield)*100
#109.22% increase

L2_0 <-subset(LiAc0.02_yield, Generation == "0")
L2_5 <-subset(LiAc0.02_yield, Generation == "500")
#Max at 500 gens
((L2_5$mean_yield-L2_0$mean_yield)/L2_0$mean_yield)*100
#118.18% increase
L2_7 <-subset(LiAc0.02_yield, Generation == "700")
#Endpoint of adaptation
((L2_7$mean_yield-L2_0$mean_yield)/L2_0$mean_yield)*100
#87.41% increase

E0 <- subset(EtOH_yield, Generation == "0")
E1 <- subset(EtOH_yield, Generation == "100")
#Max at 100 gens
((E1$mean_yield-E0$mean_yield)/E0$mean_yield*-1)*100
#27.75% increase
E1K <-subset(EtOH_yield, Generation == "1000")
#Endpoint of adaptation
((E1K$mean_yield-E0$mean_yield)/E0$mean_yield*-1)*100
#84.50% decrease

#####Novel environment stats#####

NaCl_novel <- read.delim("Stats/Parents_NaCl_Novel.txt")
NaCl_novel$Replicate <- as.factor(NaCl_novel$Replicate)
LiAc0.01_novel <- read.delim("Stats/Parents_LiAc0.01_Novel.txt")
LiAc0.01_novel$Replicate <- as.factor(LiAc0.01_novel$Replicate)
LiAc0.02_novel <- read.delim("Stats/Parents_LiAc0.02_Novel.txt")
LiAc0.02_novel$Replicate <- as.factor(LiAc0.02_novel$Replicate)
EtOH_novel <- read.delim("Stats/Parents_EtOH_Novel.txt")
EtOH_novel$Replicate <- as.factor(EtOH_novel$Replicate)

All_novel <- rbind(NaCl_novel, LiAc0.01_novel, LiAc0.02_novel, EtOH_novel)
All_novel$Population <- as.factor(All_novel$Population)

####linear mixed effect models####

library(lme4)
library(MASS)
library(emmeans)
library(car)

#####Novel environments#####
#Does fitness in novel environments change with generation?
#If so, what is the R
fm1 <- lmer(Phenotypes.ExperimentGrowthYield~ Generation + (1|Replicate), data = NaCl_novel)
#make model - fixed effect = Gens, random effect = replicate, response variable = yield in novel environments
fligner.test(Phenotypes.ExperimentGrowthYield ~ Generation, data = NaCl_novel)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Replicate, data = NaCl_novel)
#test for equal variance. All p<0.05
plot(fm1)
#boxcox(Phenotypes.ExperimentGrowthYield ~ Generation, data = NaCl_novel)
#Try ^0.5
NaCl_novel$Transformed_Phenotypes.ExperimentGrowthYield <- NaCl_novel$Phenotypes.ExperimentGrowthYield^0.5
boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = NaCl_novel)
fm1 <- lmer(Transformed_Phenotypes.ExperimentGrowthYield~ Generation + (1|Replicate), data = NaCl_novel)
#make model
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = NaCl_novel)
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Replicate, data = NaCl_novel)
#test for equal variance. RY~Gen - p<0.05
plot(fm1)
summary(fm1)
Anova(fm1)
#chi-sq = 6.71, df = 1, p < 0.01
cor.test(NaCl_novel$Phenotypes.ExperimentGrowthYield, NaCl_novel$Generation)


fm1 <- lmer(Phenotypes.ExperimentGrowthYield~ Generation + (1|Replicate), data = LiAc0.01_novel)
#make model
fligner.test(Phenotypes.ExperimentGrowthYield ~ Generation, data = LiAc0.01_novel)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Replicate, data = LiAc0.01_novel)
#test for equal variance. ~All p<0.05
plot(fm1)
#boxcox(Phenotypes.ExperimentGrowthYield ~ Generation*Replicate, data = LiAc0.01_novel)
#Try ^0.5
LiAc0.01_novel$Transformed_Phenotypes.ExperimentGrowthYield <- LiAc0.01_novel$Phenotypes.ExperimentGrowthYield^0.35
boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = LiAc0.01_novel)
fm1 <- lmer(Transformed_Phenotypes.ExperimentGrowthYield~ Generation + (1|Replicate), data = LiAc0.01_novel)
#make model
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = LiAc0.01_novel)
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Replicate, data = LiAc0.01_novel)
#test for equal variance. All p>0.05
plot(fm1)
summary(fm1)
Anova(fm1)
#chi-sq = 0.7, df = 1, p > 0.05
cor.test(LiAc0.01_novel$Phenotypes.ExperimentGrowthYield, LiAc0.01_novel$Generation)

fm1 <- lmer(Phenotypes.ExperimentGrowthYield~ Generation + (1|Replicate), data = LiAc0.02_novel)
#make model
fligner.test(Phenotypes.ExperimentGrowthYield ~ Generation, data = LiAc0.02_novel)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Replicate, data = LiAc0.02_novel)
#test for equal variance. All p<0.05
plot(fm1)
#boxcox(Phenotypes.ExperimentGrowthYield ~ Generation*Replicate, data = LiAc0.02_novel)
#boxcox suggests ^3.5 transformation
LiAc0.02_novel$Transformed_Phenotypes.ExperimentGrowthYield <- LiAc0.02_novel$Phenotypes.ExperimentGrowthYield^0.35
boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = LiAc0.02_novel)
fm1 <- lmer(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation + (1|Replicate), data = LiAc0.02_novel)
#make model
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = LiAc0.02_novel)
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Replicate, data = LiAc0.02_novel)
#test for equal variance. All p>0.05
plot(fm1)
summary(fm1)
Anova(fm1)
#chi-sq = 0.11, df = 1, p > 0.05
cor.test(LiAc0.02_novel$Phenotypes.ExperimentGrowthYield, LiAc0.02_novel$Generation)

fm1 <- lmer(Phenotypes.ExperimentGrowthYield~ Generation + (1|Replicate), data = EtOH_novel)
#make model
fligner.test(Phenotypes.ExperimentGrowthYield ~ Generation, data = EtOH_novel)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Replicate, data = EtOH_novel)
#test for equal variance. All p<0.05
plot(fm1)
#boxcox(Phenotypes.ExperimentGrowthYield ~ Generation*Replicate, data = EtOH_novel)
#boxcox suggests ^3.5 transformation
EtOH_novel$Transformed_Phenotypes.ExperimentGrowthYield <- EtOH_novel$Phenotypes.ExperimentGrowthYield^0.35
boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = EtOH_novel)
fm1 <- lmer(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation + (1|Replicate), data = EtOH_novel)
#make model
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Generation, data = EtOH_novel)
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Replicate, data = EtOH_novel)
#test for equal variance. All p<0.05 but improved
plot(fm1)
summary(fm1)
Anova(fm1)
#chi-sq = 10.25, df = 1, p < 0.01
cor.test(EtOH_novel$Phenotypes.ExperimentGrowthYield, EtOH_novel$Generation)

fm1 <- lm(Phenotypes.ExperimentGrowthYield~ Population, data = All_novel)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Population, data = All_novel)
#test for equal variance. p<0.05
plot(fm1)
All_novel$Transformed_Phenotypes.ExperimentGrowthYield <- All_novel$Phenotypes.ExperimentGrowthYield^0.4
boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = All_novel)
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = All_novel)
#test for equal variance. p<0.05
fm1 <- lm(Transformed_Phenotypes.ExperimentGrowthYield~ Population, data = All_novel)
plot(fm1)
summary(fm1)
Anova(fm1)


emm <- emmeans(fm1, ~ Population)
All <- contrast(emm, "pairwise", simple = "Population", combine = TRUE, adjust = "bonferroni")
#Tukey HSD post-hoc test for pairwise comparisons of replicates at all generations
write.table(All, file = "Stats/All_Novel_stats.txt", sep = "\t", row.names = F)
All <- read.delim("Stats/All_Novel_stats.txt")
All$Significance <- ifelse(All$p.value <= 0.001, "***", ifelse(All$p.value <= 0.01, "**", ifelse(All$p.value <= 0.05, "*", "ns")))
write.table(All, file = "Stats/All_Novel_stats.txt", sep = "\t", row.names = F)

#####Home and "away" environments#####
#How do populations compare in their home environments between the two parents and their offspring?
library(MASS)
library(emmeans)
library(car)

NaCl <- read.delim("Stats/NaCl_Fitness.txt")
NaCl$Population <- as.factor(NaCl$Population)
LiAc0.01 <- read.delim("Stats/LiAc0.01_Fitness.txt")
LiAc0.01$Population <- as.factor(LiAc0.01$Population)
LiAc0.02 <- read.delim("Stats/LiAc0.02_Fitness.txt")
LiAc0.02$Population <- as.factor(LiAc0.02$Population)
EtOH <- read.delim("Stats/EtOH_Fitness.txt")
EtOH$Population <- as.factor(EtOH$Population)

#Note above txt files generated by parental environment script

#NaCl
fm1 <- lm(Phenotypes.ExperimentGrowthYield~ Population, data = NaCl)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Population, data = NaCl)
#test for equal variance. p<0.05
plot(fm1)
#NaCl$Transformed_Phenotypes.ExperimentGrowthYield <- NaCl$Phenotypes.ExperimentGrowthYield
boxcox(Phenotypes.ExperimentGrowthYield ~ Population, data = NaCl)
#fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = NaCl)
#test for equal variance. p<0.05
#fm1 <- lm(Transformed_Phenotypes.ExperimentGrowthYield~ Population, data = NaCl)
#plot(fm1)
summary(fm1)
Anova(fm1)
#F = 34.45, df = 6, p < 0.001

emm <- emmeans(fm1, ~ Population)
All <- contrast(emm, "pairwise", simple = "Population", combine = TRUE, adjust = "bonferroni")
#Tukey HSD post-hoc test for pairwise comparisons of replicates at all generations
write.table(All, file = "Stats/NaCl_stats.txt", sep = "\t", row.names = F)
All <- read.delim("Stats/NaCl_stats.txt")
All$Significance <- ifelse(All$p.value <= 0.001, "***", ifelse(All$p.value <= 0.01, "**", ifelse(All$p.value <= 0.05, "*", "ns")))
write.table(All, file = "Stats/NaCl_stats.txt", sep = "\t", row.names = F)

#LiAc0.01
fm2 <- lm(Phenotypes.ExperimentGrowthYield~ Population, data = LiAc0.01)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.01)
#test for equal variance. p<0.05
plot(fm2)
boxcox(Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.01)
LiAc0.01$Transformed_Phenotypes.ExperimentGrowthYield <- LiAc0.01$Phenotypes.ExperimentGrowthYield^1.15
boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.01)
fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.01)
#test for equal variance. p<0.05
fm2 <- lm(Transformed_Phenotypes.ExperimentGrowthYield~ Population, data = LiAc0.01)
plot(fm2)
summary(fm2)
Anova(fm2)
#F = 732.1, df = 3, p < 0.001

emm <- emmeans(fm2, ~ Population)
All <- contrast(emm, "pairwise", simple = "Population", combine = TRUE, adjust = "bonferroni")
#Tukey HSD post-hoc test for pairwise comparisons of replicates at all generations
write.table(All, file = "Stats/LiAc0.01_stats.txt", sep = "\t", row.names = F)
All <- read.delim("Stats/LiAc0.01_stats.txt")
All$Significance <- ifelse(All$p.value <= 0.001, "***", ifelse(All$p.value <= 0.01, "**", ifelse(All$p.value <= 0.05, "*", "ns")))
write.table(All, file = "Stats/LiAc0.01_stats.txt", sep = "\t", row.names = F)

#LiAc0.02
fm3 <- lm(Phenotypes.ExperimentGrowthYield~ Population, data = LiAc0.02)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.02)
#test for equal variance. p<0.05
plot(fm3)
boxcox(Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.02)
#LiAc0.02$Transformed_Phenotypes.ExperimentGrowthYield <- LiAc0.02$Phenotypes.ExperimentGrowthYield^1
#boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.02)
#fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = LiAc0.02)
#test for equal variance. p<0.05
#fm3 <- lm(Transformed_Phenotypes.ExperimentGrowthYield~ Population, data = LiAc0.02)
#plot(fm3)
summary(fm3)
Anova(fm3)
#F = 409.2, df = 3, p < 0.001

emm <- emmeans(fm3, ~ Population)
All <- contrast(emm, "pairwise", simple = "Population", combine = TRUE, adjust = "bonferroni")
#Tukey HSD post-hoc test for pairwise comparisons of replicates at all generations
write.table(All, file = "Stats/LiAc0.02_stats.txt", sep = "\t", row.names = F)
All <- read.delim("Stats/LiAc0.02_stats.txt")
All$Significance <- ifelse(All$p.value <= 0.001, "***", ifelse(All$p.value <= 0.01, "**", ifelse(All$p.value <= 0.05, "*", "ns")))
write.table(All, file = "Stats/LiAc0.02_stats.txt", sep = "\t", row.names = F)

#EtOH
fm4 <- lm(Phenotypes.ExperimentGrowthYield~ Population, data = EtOH)
fligner.test(Phenotypes.ExperimentGrowthYield ~ Population, data = EtOH)
#test for equal variance. p<0.05
plot(fm4)
boxcox(Phenotypes.ExperimentGrowthYield ~ Population, data = EtOH)
#EtOH$Transformed_Phenotypes.ExperimentGrowthYield <- EtOH$Phenotypes.ExperimentGrowthYield^1.1
#boxcox(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = EtOH)
#fligner.test(Transformed_Phenotypes.ExperimentGrowthYield ~ Population, data = EtOH)
#test for equal variance. p<0.05
#fm4 <- lm(Transformed_Phenotypes.ExperimentGrowthYield~ Population, data = EtOH)
#plot(fm4)
summary(fm4)
Anova(fm4)
#F = 542.7, df = 3, p < 0.001

emm <- emmeans(fm4, ~ Population)
All <- contrast(emm, "pairwise", simple = "Population", combine = TRUE, adjust = "bonferroni")
#Tukey HSD post-hoc test for pairwise comparisons of replicates at all generations
write.table(All, file = "Stats/EtOH_stats.txt", sep = "\t", row.names = F)
All <- read.delim("Stats/EtOH_stats.txt")
All$Significance <- ifelse(All$p.value <= 0.001, "***", ifelse(All$p.value <= 0.01, "**", ifelse(All$p.value <= 0.05, "*", "ns")))
write.table(All, file = "Stats/EtOH_stats.txt", sep = "\t", row.names = F)

#####Parental Phenotypic Divergence#####

library(lme4)
library(car)
library(DHARMa)

ExN <- read.delim("Stats/ExN_Parents_phenotype.txt")
ExN$Replicate <- as.factor(ExN$Replicate)
ExN$FitDifferences[ExN$FitDifferences=="-1"]<-"1"
ExN$FitDifferences <- as.factor(ExN$FitDifferences)
ExN$Generation <- as.factor(ExN$Generation)
ExN$Population[ExN$Population=="P2"]<-"EtOH"

L1xN <- read.delim("Stats/ExL1_Parents_phenotype.txt")
L1xN$Replicate <- as.factor(L1xN$Replicate)
L1xN$FitDifferences[L1xN$FitDifferences=="-1"]<-"1"
L1xN$FitDifferences <- as.factor(L1xN$FitDifferences)
L1xN$Generation <- as.factor(L1xN$Generation)
L1xN$Population[L1xN$Population=="P2"]<-"LiAc0.01"

L2xN <- read.delim("Stats/ExL2_Parents_phenotype.txt")
L2xN$Replicate <- as.factor(L2xN$Replicate)
L2xN$FitDifferences[L2xN$FitDifferences=="-1"]<-"1"
L2xN$FitDifferences <- as.factor(L2xN$FitDifferences)
L2xN$Generation <- as.factor(L2xN$Generation)
L2xN$Population[L2xN$Population=="P2"]<-"LiAc0.02"

#Note - above files generated by parental divergence script

fm1 <- glm(FitDifferences~Generation, data = ExN, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm1)
Anova(fm1)
#chi-sq = 19.80, df = 5, p < 0.001
#VarCorr(fm1)

fm2 <- glm(FitDifferences~Generation, data = L1xN, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm2)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm2)
Anova(fm2)
#chi-sq = 12.45, df = 4, p < 0.05
#VarCorr(fm2)

fm3 <- glm(FitDifferences~Generation, data = L2xN, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq = 4.82, df = 4, p > 0.05
#VarCorr(fm3)


#####Heterosis/Dominance categories in F1 hybrids with varying Parental Divergence#####

library(lme4)
library(car)
library(DHARMa)
#library(pscl)

F1_NL1 <- read.delim("Stats/Heterosis_F1s_Cross1Yield.txt")
F1_NL1$Replicate <- as.factor(F1_NL1$Replicate)
F1_NL1$dominance_category <- as.factor(F1_NL1$dominance_category)
F1_NL1$overdominance <- as.factor(F1_NL1$overdominance)
F1_NL1$Generation <- as.factor(F1_NL1$Generation)


F1_NL2 <- read.delim("Stats/Heterosis_F1s_Cross2Yield.txt")
F1_NL2$Replicate <- as.factor(F1_NL2$Replicate)
F1_NL2$dominance_category <- as.factor(F1_NL2$dominance_category)
F1_NL2$overdominance <- as.factor(F1_NL2$overdominance)
F1_NL2$Generation <- as.factor(F1_NL2$Generation)

F1_NE <- read.delim("Stats/Heterosis_F1s_Cross3Yield.txt")
F1_NE$Replicate <- as.factor(F1_NE$Replicate)
F1_NE$dominance_category <- as.factor(F1_NE$dominance_category)
F1_NE$overdominance <- as.factor(F1_NE$overdominance)
F1_NE$Generation <- as.factor(F1_NE$Generation)

#Note - above files generated from heterosis.R script

fm1 <- glm(overdominance~Generation*Replicate, data = F1_NL1, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(overdominance~Generation + Replicate, data = F1_NL1, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(overdominance~Generation, data = F1_NL1, family=binomial)
fm4 <- glm(overdominance~Replicate, data = F1_NL1, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq = 28.15, df = 2, p < 0.001
#VarCorr(fm1)

fm1 <- glm(overdominance~Generation*Replicate, data = F1_NL2, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(overdominance~Generation + Replicate, data = F1_NL2, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(overdominance~Generation, data = F1_NL2, family=binomial)
fm4 <- glm(overdominance~Replicate, data = F1_NL2, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq = 13.23, df = 2, p < 0.01
#VarCorr(fm1)

fm1 <- glm(overdominance~Generation*Replicate, data = F1_NE, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(overdominance~Generation + Replicate, data = F1_NE, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(overdominance~Generation, data = F1_NE, family=binomial)
fm4 <- glm(overdominance~Replicate, data = F1_NE, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq = 2.50, df = 2, p > 0.05
#VarCorr(fm1)

#####Transgression and Parental Divergence#####

#Positive transgression
F2_NL1 <- read.delim("Stats/Transgressive_F2s_Cross1Yield.txt")
F2_NL1$Generation <- as.factor(F2_NL1$Generation)
F2_NL1$Transgression[F2_NL1$Transgression=="-1"]<-"0"
F2_NL1$Transgression <- as.factor(F2_NL1$Transgression)
str(F2_NL1)
#Only interested in whether transgression is positive or not here. -1 = negative transgression, changed to 0 here to reflect that
F2_NL2 <- read.delim("Stats/Transgressive_F2s_Cross2Yield.txt")
F2_NL2$Generation <- as.factor(F2_NL2$Generation)
F2_NL2$Transgression[F2_NL2$Transgression=="-1"]<-"0"
F2_NL2$Transgression <- as.factor(F2_NL2$Transgression)
str(F2_NL2)

F2_NE<- read.delim("Stats/Transgressive_F2s_Cross3Yield.txt")
F2_NE$Generation <- as.factor(F2_NE$Generation)
F2_NE$Transgression[F2_NE$Transgression=="-1"]<-"0"
F2_NE$Transgression <- as.factor(F2_NE$Transgression)
str(F2_NE)

#Note above files generated from Heterosis & Transgression.R script

fm1 <- glm(Transgression~Generation*Replicate, data = F2_NL1, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(Transgression~Generation + Replicate, data = F2_NL1, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(Transgression~Generation, data = F2_NL1, family=binomial)
fm4 <- glm(Transgression~Replicate, data = F2_NL1, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq = 9.33, df = 3, p < 0.05
#VarCorr(fm1)

fm1 <- glm(Transgression~Generation*Replicate, data = F2_NL2, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(Transgression~Generation + Replicate, data = F2_NL2, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(Transgression~Generation, data = F2_NL2, family=binomial)
fm4 <- glm(Transgression~Replicate, data = F2_NL2, family=binomial)
AIC(fm3)
AIC(fm4)
#fm2 has lowest AIC. Keep replicate and generation
simulationOutput <- simulateResiduals(fittedModel = fm2)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm2)
Anova(fm2)
#chi-sq gen = 19.83, df = 3, p < 0.001
#chi-sq rep = 10.7, df = 2, p < 0.01
#VarCorr(fm1)

fm1 <- glm(Transgression~Generation*Replicate, data = F2_NE, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(Transgression~Generation + Replicate, data = F2_NE, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(Transgression~Generation, data = F2_NE, family=binomial)
fm4 <- glm(Transgression~Replicate, data = F2_NE, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq gen = 1.73, df = 2, p > 0.05
#VarCorr(fm1)

F2_NL1 <- read.delim("Stats/Transgressive_F2s_Cross1Yield.txt")
F2_NL1$Generation <- as.factor(F2_NL1$Generation)
F2_NL1$Transgression[F2_NL1$Transgression=="1"]<-"0"
F2_NL1$Transgression[F2_NL1$Transgression=="-1"]<-"1"
F2_NL1$Transgression <- as.factor(F2_NL1$Transgression)
str(F2_NL1)
#Only interested in whether transgression is negative or not here. 1 = positive transgression, changed to 0 here to reflect that

F2_NL2 <- read.delim("Stats/Transgressive_F2s_Cross2Yield.txt")
F2_NL2$Generation <- as.factor(F2_NL2$Generation)
F2_NL2$Transgression[F2_NL2$Transgression=="1"]<-"0"
F2_NL2$Transgression[F2_NL2$Transgression=="-1"]<-"1"
F2_NL2$Transgression <- as.factor(F2_NL2$Transgression)
str(F2_NL2)

F2_NE<- read.delim("Stats/Transgressive_F2s_Cross3Yield.txt")
F2_NE$Generation <- as.factor(F2_NE$Generation)
F2_NE$Transgression[F2_NE$Transgression=="1"]<-"0"
F2_NE$Transgression[F2_NE$Transgression=="-1"]<-"1"
F2_NE$Transgression <- as.factor(F2_NE$Transgression)
str(F2_NE)

fm1 <- glm(Transgression~Generation*Replicate, data = F2_NL1, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(Transgression~Generation + Replicate, data = F2_NL1, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(Transgression~Generation, data = F2_NL1, family=binomial)
fm4 <- glm(Transgression~Replicate, data = F2_NL1, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq = 5.92, df = 3, p > 0.1
#VarCorr(fm1)

fm1 <- glm(Transgression~Generation*Replicate, data = F2_NL2, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
simulationOutput <- simulateResiduals(fittedModel = fm1)
plot(simulationOutput)
testDispersion(simulationOutput)
fm2 <- glm(Transgression~Generation + Replicate, data = F2_NL2, family=binomial)
AIC(fm1)
AIC(fm2)
#fm2 has lower AIC. Drop interaction
fm3 <- glm(Transgression~Generation, data = F2_NL2, family=binomial)
fm4 <- glm(Transgression~Replicate, data = F2_NL2, family=binomial)
AIC(fm3)
AIC(fm4)
#fm3 has lowest AIC. Drop replicate
simulationOutput <- simulateResiduals(fittedModel = fm3)
plot(simulationOutput)
testDispersion(simulationOutput)

summary(fm3)
Anova(fm3)
#chi-sq gen = 6.04, df = 3, p > 0.05
#VarCorr(fm1)

#fm1 <- glm(Transgression~Generation*Replicate, data = F2_NE, family=binomial)
#make model - fixed effect = Gens, random effect = replicate, response variable = heterosis in novel environment (binomial)
#simulationOutput <- simulateResiduals(fittedModel = fm1)
#plot(simulationOutput)
#testDispersion(simulationOutput)
#fm2 <- glm(Transgression~Generation + Replicate, data = F2_NE, family=binomial)
#AIC(fm1)
#AIC(fm2)
#fm2 has lower AIC. Drop interaction
#fm3 <- glm(Transgression~Generation, data = F2_NE, family=binomial)
#fm4 <- glm(Transgression~Replicate, data = F2_NE, family=binomial)
#AIC(fm3)
#AIC(fm4)
#fm3 has lowest AIC. Drop replicate
#simulationOutput <- simulateResiduals(fittedModel = fm3)
#plot(simulationOutput)
#testDispersion(simulationOutput)

#summary(fm3)
#Anova(fm3)
#chi-sq gen = 24.61, df = 4, p < 0.001
#VarCorr(fm1)

library(dplyr)
Heterosis_Yield <- F2_NE %>% group_by(Generation, Transgression) %>% summarise(n())
#0 negative transgression for EtOH cross